require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Include:
    - '**/*.rb'
    - '**/Rakefile'
    - '**/*.rake'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

Minitest/MultipleAssertions:
  Enabled: false

Minitest/TestCaseOrder:
  Enabled: false

Minitest/TestFileName:
  Enabled: false
