#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/script_helpers'

tournament_id = ARGV[0] || raise('tournament id argument is required')

questions = Metaculus.list_resolved_tournament_questions(tournament_id)

puts "NOTE: doesn't paginate, so will miss questions if there are more than 100"

data = []
questions.reject! { |q| q.spot_peer_score.nil? }
questions.sort_by!(&:spot_peer_score)
questions.reverse!
questions.each_with_index do |q, i|
  data << <<~QUESTION
    <forecast>
      <id>#{q.post_id}</id>
      <title>#{q.title}</title>
      <type>#{q.type}</type>
      <spot_peer_score>#{q.spot_peer_score.round}</spot_peer_score>
      <resolution>#{q.resolution}</resolution>
      <my_prediction>#{q.my_prediction}</my_prediction>
      <error>#{q.error_summary}</error>
      <my_comment>#{q.my_comment}</my_comment>
    </forecast>
  QUESTION
end

Formatador.display "\n[bold][green]# Retro: Reviewing Scores(#{tournament_id})…[/] "

provider = :deepseek
llm = Provider.new(provider, system: '')

retro_prompt = <<~RETRO_PROMPT
  These forecasts were generated by an automated multi-stage forecasting pipeline (not a single human forecaster). Your job is to analyze the pipeline's performance and recommend concrete prompt, process, and architecture improvements.

  ## Pipeline Architecture

  1. **News** — Fetches recent news articles via AskNews API for the question topic.
  2. **Research** — Deep research phase: an LLM with web search tools produces a structured research brief covering base rates, historical analogs, current situation, and key uncertainties.
  3. **Forecast** — 4 independent LLM forecasters (different providers) each produce a forecast using the same system prompt, research brief, and question context.
  4. **Revise** — Each forecaster sees the other 3 forecasts and may revise their own before final submission.
  5. **Consensus** — A meta-forecaster LLM synthesizes the 4 revised forecasts into a single consensus and submits it. The `<my_comment>` field is the meta-forecaster's synthesis writeup.

  ## Forecaster System Prompt

  The 4 forecasters all use this guidance:
  - You are a superforecaster with a track record of well-calibrated probabilistic forecasts on geopolitical, economic, and scientific questions. Maintain calibration — neither overconfident nor underconfident.
  - Assign precise, justified numerical likelihoods (e.g., 42%, 2.3%) with confidence intervals, while recognizing limits of knowledge.
  - Put extra weight on status quo outcomes since the world usually changes slowly.
  - For each adjustment to the base rate, for cognitive/source biases, or to confidence — explicitly state the direction, magnitude, supporting evidence, and reasoning.
  - Express uncertainty using both confidence intervals and verbal probabilities.
  - Provide separate uncertainty estimates for different components (parameter uncertainty, model uncertainty, outcome uncertainty).
  - Explicitly state the strongest argument against your reasoning and provide an alternative probability.
  - At the end of your forecast, provide a single, precise confidence rating.
  - Binary questions: do not assign probability below 5% or above 95% without extremely strong justification.

  ## Consensus Meta-Forecaster Prompt

  The meta-forecaster who writes `<my_comment>` is instructed to:
  - Synthesize, not re-forecast from scratch. The input forecasts have already done the analytical work.
  - Anchor on a mechanical aggregate baseline (log-odds pool with extremization for binary/multiple-choice; quantile average for numeric/discrete).
  - Weight forecasts by reasoning quality, not just stated confidence.
  - Be aware that LLMs systematically underreact and cluster probabilities near 50%. Maintain awareness of this bias.
  - Identify the 2-3 largest divergences between forecasts and explain which reasoning path is more epistemically sound.

  ## Forecast Data

  Below are the pipeline's forecasts with scores, resolutions, predictions, error analyses, and consensus comments (may be unavailable for some questions — see note).

  <forecasts>
  #{data.join.strip}
  </forecasts>

  Review this data thoroughly to improve the pipeline, then:
    - identify commonalities among the lowest and highest scores
    - analyze error patterns: direction (over/under confident), magnitude, and question-type trends
    - where consensus comments are available: evaluate whether the meta-forecaster identified the right divergences between forecasters, and whether the underlying forecaster reasoning (as reflected in the consensus synthesis) revealed flawed assumptions, missing base rates, or confirmation bias. If comments are unavailable, note this and rely on score/prediction patterns instead.
    - identify which question types the pipeline performs best/worst on and hypothesize why (prompt fit, inherent difficulty, research quality, aggregation dynamics)
    - for each error pattern, identify which pipeline stage is the most likely source: research gaps, forecaster prompt issues, revision dynamics (e.g., herding toward consensus), or consensus synthesis failures
    - recommend specific, actionable improvements to:
      a. The forecaster system prompt (instructions to add, remove, or reweight — e.g., should the status-quo bias be stronger or weaker? Are the 5%/95% floor/ceiling rules helping or hurting?)
      b. The research phase (what information should be gathered differently to prevent recurring errors)
      c. The revision phase (is seeing peer forecasts causing herding or productive refinement?)
      d. The consensus process (aggregation approach, extremization rules, divergence handling)
      e. Question-type-specific handling (prompt modifications per type — binary, numeric, discrete, multiple-choice)
    - recommend how to improve this retro analysis prompt itself to produce more actionable pipeline feedback
RETRO_PROMPT

retro = llm.eval({ 'role': 'user', 'content': retro_prompt })
puts retro.content
