#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/script_helpers'

tournament_id = ARGV[0] || raise('tournament id argument is required')

questions = Metaculus.list_resolved_tournament_questions(tournament_id)

puts "NOTE: doesn't paginate, so will miss questions if there are more than 100"

# Extract full XML elements including attributes (for self-closing-like
# elements like <forecaster provider="..." ...>content</forecaster>)
def extract_full_elements(text, tag)
  text.scan(%r{<#{tag}[^>]*>[\s\S]*?</#{tag}>}).map(&:strip)
end

data = []
questions.reject! { |q| q.spot_peer_score.nil? }
questions.sort_by!(&:spot_peer_score)
questions.reverse!
questions.each_with_index do |q, _i|
  comment_text = q.my_comment

  # Extract structured sub-tags from pipeline comments
  research_summary = extract_xml(comment_text, 'research_summary').first
  consensus_analysis = extract_xml(comment_text, 'consensus_analysis').first
  forecasters = extract_full_elements(comment_text, 'forecaster')
  final_forecast = extract_xml(comment_text, 'probability', 'percentiles', 'probabilities').first

  # Build structured comment section
  comment_tags = []
  comment_tags << "<research_summary>#{research_summary}</research_summary>" if research_summary
  forecasters.each { |f| comment_tags << "  #{f}" }
  comment_tags << "<consensus_analysis>#{consensus_analysis}</consensus_analysis>" if consensus_analysis
  comment_tags << "<final_forecast>#{final_forecast}</final_forecast>" if final_forecast
  # Fallback: include raw comment for non-pipeline questions or when no tags match
  comment_tags << "<raw_comment>#{comment_text}</raw_comment>" if comment_tags.empty? && !comment_text.empty?

  data << <<~QUESTION
    <forecast>
      <id>#{q.post_id}</id>
      <title>#{q.title}</title>
      <type>#{q.type}</type>
      <spot_peer_score>#{q.spot_peer_score.round}</spot_peer_score>
      <resolution>#{q.resolution}</resolution>
      <my_prediction>#{q.my_prediction}</my_prediction>
      <error>#{q.error_summary}</error>
      <comment>
    #{comment_tags.join("\n")}
      </comment>
    </forecast>
  QUESTION
end

Formatador.display "\n[bold][green]# Retro: Reviewing Scores(#{tournament_id})…[/] "

provider = :deepseek
llm = Provider.new(provider, system: '')

retro_prompt = <<~RETRO_PROMPT
  These forecasts were generated by an automated multi-stage forecasting pipeline: News → Research → 4 independent Forecasters → Delphi Revise (each sees peers' estimates) → Consensus.

  ## Comment Data Structure

  Pipeline-generated questions include structured XML in their comments:
  - `<research_summary>` — The research phase findings used by all forecasters
  - `<forecaster>` — Per-provider forecast with attributes:
    - `provider` — Model name (anthropic, openai, gemini, deepseek)
    - `value` — Final (post-revision) forecast value
    - `pre_revision` — Forecast value BEFORE the Delphi revise stage (enables measuring herding vs. refinement)
    - `confidence` — Self-assessed confidence rating
    - Content: Key argument summary
  - `<consensus_analysis>` — The meta-forecaster's synthesis reasoning
  - `<final_forecast>` — The submitted consensus forecast value
  - `<raw_comment>` — Fallback for questions without pipeline-structured comments

  Questions without pipeline comments use `<raw_comment>` only — analyze these using score/prediction patterns.

  ## Forecaster System Prompt (verbatim)

  #{SUPERFORECASTER_SYSTEM_PROMPT}

  ## Delphi Revision Prompt Template

  #{File.read('lib/prompt_templates/forecast_delphi.erb')}

  ## Consensus Meta-Forecaster System Prompt (verbatim)

  #{CONSENSUS_SYSTEM_PROMPT}

  ### Consensus Meta-Forecaster Prompt Template

  #{File.read('lib/prompt_templates/forecast_consensus.erb')}

  ## Forecast Data

  <forecasts>
  #{data.join.strip}
  </forecasts>

  Review this data thoroughly to improve the pipeline, then:
    - identify commonalities among the lowest and highest scores
    - analyze error patterns: direction (over/under confident), magnitude, and question-type trends
    - where structured comment data is available: evaluate forecaster-level performance by provider — do certain providers consistently outperform? Is the Delphi revision stage causing herding (convergence toward median without accuracy gain, visible in pre_revision vs. value) or productive refinement (movement toward resolution)?
    - evaluate whether the meta-forecaster identified the right divergences between forecasters, and whether the underlying forecaster reasoning revealed flawed assumptions, missing base rates, or confirmation bias
    - assess research quality by comparing `<research_summary>` content against question outcomes — are there recurring research gaps?
    - identify which question types the pipeline performs best/worst on and hypothesize why (prompt fit, inherent difficulty, research quality, aggregation dynamics)
    - for each error pattern, identify which pipeline stage is the most likely source: research gaps, forecaster prompt issues, revision dynamics (e.g., herding toward consensus), or consensus synthesis failures
    - recommend specific, actionable improvements to:
      a. The forecaster system prompt (instructions to add, remove, or reweight — e.g., should the status-quo bias be stronger or weaker? Are the 5%/95% floor/ceiling rules helping or hurting?)
      b. The research phase (what information should be gathered differently to prevent recurring errors)
      c. The revision phase (is seeing peer forecasts causing herding or productive refinement? Use pre_revision vs. value data)
      d. The consensus process (aggregation approach, extremization rules, divergence handling)
      e. Question-type-specific handling (prompt modifications per type — binary, numeric, discrete, multiple-choice)
    - recommend how to improve this retro analysis prompt itself to produce more actionable pipeline feedback
RETRO_PROMPT

retro = llm.eval({ 'role': 'user', 'content': retro_prompt })
puts retro.content
