name: fall-aib-2025 Executor

on:
  workflow_dispatch:
  schedule:
    - cron: "5/15 * * * *" # run every 15 minutes, starting at 5 past the hour

jobs:
  query:
    concurrency:
      group: scheduled-forecast-query
      cancel-in-progress: false
    outputs:
      post_ids: ${{ steps.post_ids.outputs.post_ids }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - id: post_ids
        run: |
          echo "post_ids=$(./tournament_questions.rb fall-aib-2025)" >> $GITHUB_OUTPUT
        env:
          METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
          METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}

  enqueue:
    if: ${{ needs.query.outputs.post_ids != '[]' }}
    needs: query
    strategy:
      matrix:
        post_id: ${{ fromJSON(needs.query.outputs.post_ids) }}
    concurrency:
      group: scheduled-forecast-enqueue
      cancel-in-progress: false
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
      METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
    uses: ./.github/workflows/forecast.yml
    with:
      post_id: ${{ matrix.post_id }}
