name: Forecast Test

on:
  workflow_dispatch:

# prevent parallel runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  forecast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: ./forecast.rb 578
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
          METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
