name: Forecasts Test

on:
  workflow_dispatch:
    inputs:
      post_id:
        description: 'Metaculus post id to forecast:'
        default: '578'
        type: string

# prevent parallel runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - run: mv ./artifact ./tmp
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: ./research.rb ${{ inputs.post_id }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
          METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          path: tmp
      - run: |
          echo "# $(cat tmp/${{ inputs.post_id }}/post.json | jq -r '.title')" >> $GITHUB_STEP_SUMMARY
          echo "$(cat tmp/${{ inputs.post_id }}/post.json | jq -r '.question.description')" >> $GITHUB_STEP_SUMMARY

  forecast:
    needs: research
    runs-on: ubuntu-latest
    strategy:
      matrix:
        forecaster_index: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - run: |
          [ -d artifact ] && mv ./artifact ./tmp
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: ./forecast.rb ${{ inputs.post_id }} ${{ matrix.forecaster_index }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
          METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          path: tmp/${{ inputs.post_id }}/forecasts/forecast.${{ matrix.forecaster_index }}.json

  revise_forecast:
    needs: forecast
    runs-on: ubuntu-latest
    strategy:
      matrix:
        forecaster_index: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - run: mv ./artifact ./tmp
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: ./revise_forecast.rb ${{ inputs.post_id }} ${{ matrix.forecaster_index }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
          METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          path: tmp/${{ inputs.post_id }}/forecasts/revision.${{ matrix.forecaster_index }}.json

  finalize:
    needs: revise_forecast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - run: mv ./artifact ./tmp
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: |
          echo "# Results"
          echo "```json" >> $GITHUB_STEP_SUMMARY
          echo "# $(cat tmp/${{ inputs.post_id }}/consensus/forecast.json | jq -r '.')" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          echo "$(cat tmp/${{ inputs.post_id }}/consensus/comment.json | jq -r '.text')" >> $GITHUB_STEP_SUMMARY
