name: minibench Executor

on:
  workflow_dispatch:
  schedule:
    - cron: "10/20 * * * *" # run every 20 minutes, starting at 10 past the hour

jobs:
  query:
    concurrency:
      group: scheduled-forecast-query
      cancel-in-progress: false
    outputs:
      post_ids: ${{ steps.post_ids.outputs.post_ids }}
    runs-on: ubuntu-latest
    steps:
      - id: post_ids
        run: |
          curl "https://www.metaculus.com/api/posts/?forecast_type=binary,discrete,multiple_choice,numeric&include_description=true&not_forecaster_id=$METACULUS_BOT_ID&offset=0&statuses=open&tournaments=minibench" -H "Authorization: Token $METACULUS_BOT_API_TOKEN" \
            | jq -c '.results | map(.id)' >> $GITHUB_OUTPUT
        env:
          METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
          METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}

  enqueue:
    if: ${{ needs.query.outputs.post_ids != '[]' }}
    needs: query
    strategy:
      matrix:
        post_id: ${{ fromJSON(needs.query.outputs.post_ids) }}
    concurrency:
      group: scheduled-forecast-enqueue
      cancel-in-progress: false
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
      METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
    uses: ./.github/workflows/forecast.yml
    with:
      post_id: ${{ matrix.post_id }}
