name: Scheduler Testing

on:
  workflow_dispatch:

jobs:
  query:
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false
    outputs:
      post_ids: ${{ steps.post_ids.outputs.post_ids }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - id: post_ids
        run: |
          # ./tournament_questions.rb minibench
          # echo "POST_IDS=$(./tournament_questions.rb minibench)" >> $GITHUB_OUTPUT
          # echo "post_ids=[]" >> $GITHUB_OUTPUT
          echo "post_ids=[578,22427]" >> $GITHUB_OUTPUT
        env:
          METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
          METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}

  enqueue:
    if: ${{ needs.query.outputs.post_ids != '[]' }}
    needs: query
    strategy:
      matrix:
        post_id: ${{ fromJSON(needs.query.outputs.post_ids) }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.post_id }}
      cancel-in-progress: false
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
      METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
    uses: ./.github/workflows/forecast.yml
    with:
      post_id: ${{ matrix.post_id }}
