on:
  workflow_dispatch:

jobs:
  self-destruction:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - run: |
          gh runs delete --repo ${{ github.repository }} ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
